# Generated by Django 4.2.1 on 2023-05-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="position",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
