# Generated by Django 4.2.1 on 2024-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_photo_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterField(
            model_name="photo",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
