# Generated by Django 4.2.1 on 2024-03-17 17:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_alter_photo_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(),
        ),
    ]
