# Generated by Django 4.2.1 on 2024-03-21 17:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="places.place",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.FloatField(verbose_name="Широта в градусах"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lng",
            field=models.FloatField(verbose_name="Долгота в градусах"),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Название места"
            ),
        ),
    ]
