# Generated by Django 4.2.1 on 2024-03-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0007_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="places.place",
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Позиция"),
        ),
    ]
