# Generated by Django 4.2.1 on 2024-03-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0008_alter_photo_place_alter_photo_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo",
            field=models.ImageField(upload_to="places", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="position",
            field=models.IntegerField(blank=True, default=0, verbose_name="Позиция"),
        ),
        migrations.AlterField(
            model_name="place",
            name="short_description",
            field=models.TextField(verbose_name="Короткое описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название места"),
        ),
    ]
