# Generated by Django 4.2.1 on 2024-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0009_alter_photo_photo_alter_photo_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="position",
            field=models.IntegerField(
                blank=True, db_index=True, default=0, verbose_name="Позиция"
            ),
        ),
    ]
